import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/components/navbar";
import AppProvider from "@/components/provider";
import "@/styles/globals.css";
import { Suspense } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <AppProvider>
          <>
            <Suspense>
              <Navbar />
            </Suspense>
            <div
              className="w-screen"
              style={{
                height: "calc(100vh - 90px)",
              }}
            >
              {children}
            </div>
          </>
        </AppProvider>
      </body>
    </html>
  );
}
